version: '3'

services:
  web:
    build: .
    working_dir: /code
    env_file:
      - ./api.env
    command: bash -c "python ./sol_api/manage.py makemigrations && python ./sol_api/manage.py migrate && python ./sol_api/manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/code
    ports:
      - "8000:8000"